/* lavagne-nuove/maree-onde.js — buchi del programma cap. 9 e 11 */

LAV.gravitazione = [

{type:6, topic:"Maree",
 q:"Deduca la forza mareale come forza differenziale nel riferimento solidale con la Terra in caduta libera verso la Luna: ricavi il campo mareale al primo ordine in $R_T/d$ lungo la congiungente e in direzione trasversa, spieghi perch&eacute; i rigonfiamenti sono due e commenti la dipendenza $1/d^3$.",
 prov:"Gravitazione — canone universale (da ricontrollare sul Focardi, copia fisica)",
 model:"<b>Riferimento in caduta libera.</b> Tutta la Terra cade verso la Luna con $a_0=GM_L/d^2$ ($d$ fra i centri). Nel riferimento del centro della Terra, traslante e non rotante, compare la forza apparente uniforme $-m\\mathbf{a}_0$: ogni punto sente allora una forza <b>differenziale</b> $$\\mathbf{F}_{tid}=m\\left[\\mathbf{g}_L(\\mathbf{r})-\\mathbf{g}_L(\\mathbf{0})\\right],$$ che sarebbe nulla se $\\mathbf{g}_L$ fosse uniforme: la marea vive della sua disomogeneit&agrave;. <b>Lungo la congiungente.</b> Asse $x$ verso la Luna, origine nel centro; l'attrazione in $x$ ha modulo $GM_L/(d-x)^2$, quindi $$\\Delta g_x=\\frac{GM_L}{d^2}\\left[\\left(1-\\frac{x}{d}\\right)^{-2}-1\\right]\\simeq\\frac{2GM_Lx}{d^3},$$ avendo sviluppato al primo ordine in $x/d$, lecito perch&eacute; $R_T/d\\approx1/60$ (dato astronomico, non derivato qui). <b>Trasversalmente.</b> Per $\\mathbf{r}=(0,y)$ la componente $y$ vale $-GM_Ly/(d^2+y^2)^{3/2}\\simeq-GM_Ly/d^3$, mentre al centro era nulla. Sulla superficie: $$\\boxed{\\ a_{\\parallel}=+\\frac{2GM_LR_T}{d^3},\\qquad a_{\\perp}=-\\frac{GM_LR_T}{d^3}\\ }$$ <b>Perch&eacute; i bozzi sono due.</b> In $x=+R_T$ il campo punta verso la Luna; in $x=-R_T$ &egrave; negativo, cio&egrave; punta ancora <b>via dal centro</b>, stavolta in verso opposto alla Luna. Estensivo sulle due calotte, compressivo sull'anello trasverso: l'oceano si solleva in due rigonfiamenti opposti, agganciati alla direzione Terra-Luna mentre la Terra ruota sotto di essi. Un punto ne attraversa due per rotazione: <b>due alte maree</b> al giorno, a poco pi&ugrave; di dodici ore l'una dall'altra perch&eacute; intanto la Luna avanza in orbita. $\\blacksquare$<br><br><b>Significato fisico.</b> La marea va come $1/d^3$ e non come $1/d^2$ perch&eacute; misura la <b>derivata</b> del campo, non il campo; di qui il confronto Luna-Sole, senza numeri inventati: $$\\frac{a_{tid,L}}{a_{tid,S}}=\\frac{a_{grav,L}}{a_{grav,S}}\\cdot\\frac{d_S}{d_L}.$$ Il Sole attrae la Terra molto pi&ugrave; della Luna, ma &egrave; circa quattrocento volte pi&ugrave; lontano (dato astronomico): il secondo fattore ribalta il primo e la Luna vince. Ipotesi dichiarate: Terra sferica, oceano in equilibrio istantaneo (teoria statica di Newton), primo ordine in $R_T/d$. La traccia nulla del campo, $2-1-1=0$, riflette $\\nabla^2\\Phi=0$ nel vuoto; in relativit&agrave; generale lo stesso tensore $\\partial_i\\partial_j\\Phi$ &egrave; l'equazione di deviazione geodetica, e la marea diventa il modo operativo di misurare la curvatura."}

];

LAV.onde = [

{type:6, topic:"Onde piane e sferiche",
 q:"Parta dalla conservazione dell'energia attraverso superfici d'onda concentriche e ricavi l'andamento di intensit&agrave; e ampiezza di un'onda sferica; verifichi poi che $y(r,t)=(A_0/r)\\sin(kr-\\omega t)$ risolve l'equazione delle onde in simmetria sferica e confronti il caso dell'onda piana.",
 prov:"Onde — canone universale (da ricontrollare sul Focardi, copia fisica)",
 model:"<b>Conservazione dell'energia.</b> Sorgente puntiforme in un mezzo omogeneo, isotropo e non dissipativo, di potenza media $P$ costante. Le superfici d'onda sono sfere concentriche e la stessa potenza attraversa ciascuna di esse: $$P=I(r)\\,4\\pi r^2\\ \\Longrightarrow\\ I(r)=\\frac{P}{4\\pi r^2}\\propto\\frac{1}{r^2}.$$ <b>Dall'intensit&agrave; all'ampiezza.</b> Per un'onda armonica la densit&agrave; media di energia &egrave; $\\bar u=\\tfrac12\\rho\\,\\omega^2A^2$ e $I=\\bar u\\,v$, dunque $I\\propto A^2$; da $A^2\\propto1/r^2$ segue $A(r)=A_0/r$. <b>Il laplaciano radiale: il cuore della verifica.</b> Per $y=y(r,t)$ vale $\\nabla^2y=\\frac{1}{r^2}\\partial_r(r^2\\partial_r y)$. Pongo $u=r\\,y$: allora $\\partial_r y=u'/r-u/r^2$, quindi $r^2\\partial_r y=r\\,u'-u$ e $$\\partial_r\\left(r^2\\partial_r y\\right)=u'+r\\,u''-u'=r\\,u''\\ \\Longrightarrow\\ \\nabla^2y=\\frac{1}{r}\\partial_{rr}(ry).$$ <b>Riduzione a d'Alembert unidimensionale.</b> Moltiplicando $\\partial_{tt}y=v^2\\nabla^2y$ per $r$ si ottiene $\\partial_{tt}(ry)=v^2\\partial_{rr}(ry)$: la funzione $u=ry$ obbedisce all'equazione delle onde in una dimensione. Le sue soluzioni progressive sono $u=f(r-vt)$; scegliendo l'armonica $u=A_0\\sin(kr-\\omega t)$ con $\\omega=vk$, $$\\boxed{\\ y(r,t)=\\frac{A_0}{r}\\sin(kr-\\omega t)\\ },\\qquad r>0.$$ Il fattore $1/r$ non &egrave; aggiunto a mano: lo impone l'equazione, in accordo col bilancio energetico. $\\blacksquare$ <b>Onda piana.</b> Se i fronti sono piani paralleli l'area attraversata non cresce: $I$ e $A$ restano costanti e $y=A\\sin(kx-\\omega t)$ risolve d'Alembert senza fattore geometrico. &Egrave; un'idealizzazione, perch&eacute; un fronte piano infinito trasporterebbe potenza infinita.<br><br><b>Significato fisico.</b> Lontano dalla sorgente l'onda sferica &egrave; localmente piana: su un tratto radiale $\\Delta r\\ll r_0$ il fattore $1/r$ varia in relativo di $\\Delta r/r_0\\ll1$, e su un'apertura trasversa $D$ la freccia del fronte, $s=r_0-\\sqrt{r_0^2-D^2/4}\\simeq D^2/(8r_0)$, &egrave; trascurabile rispetto a $\\lambda$ se $r_0\\gg D^2/\\lambda$ (campo lontano, o condizione di Fraunhofer): il fronte curvo si confonde col piano tangente. Il $1/r^2$ dell'intensit&agrave; &egrave; la stessa geometria del $1/r^2$ di Newton e Coulomb, un flusso conservato spalmato su $4\\pi r^2$; e la forma $e^{ikr}/r$ ritorna nei potenziali ritardati e, in meccanica quantistica, nell'onda diffusa dello scattering, $\\psi\\sim e^{ikz}+f(\\theta)\\,e^{ikr}/r$."}

];
