/* lavagne-nuove/rigidi.js — buchi del programma cap. 8 */
LAV.rigidi = [

{type:6, topic:"Moti giroscopici — precessione del giroscopio",
 q:"Ricava la velocit&agrave; angolare di precessione $\\Omega_p$ di una trottola simmetrica appoggiata in un punto, partendo dalla seconda equazione cardinale. Spiega perch&eacute; il momento della forza peso cambia la direzione di $\\vec L$ ma non il suo modulo, e dichiara esattamente che cosa si trascura nell'approssimazione giroscopica.",
 prov:"Corpi rigidi — canone universale (da ricontrollare sul Focardi, copia fisica)",
 model:"<b>Sistema e ipotesi.</b> Corpo a simmetria assiale vincolato in $O$: asse di figura principale d'inerzia con momento $I$, inclinato di $\\theta$ sulla verticale $\\hat z$, centro di massa sull'asse a distanza $d$ da $O$, spin $\\omega$. <b>Ipotesi giroscopica:</b> si pone $\\vec L\\simeq I\\omega\\,\\hat u$ lungo l'asse di figura, cio&egrave; si <b>trascura</b> il momento angolare generato dalla precessione stessa ($I_\\perp\\Omega_p\\sin\\theta\\ll I\\omega$), la nutazione e l'attrito in $O$.<br><b>Il momento &egrave; ortogonale a $\\vec L$.</b> Il peso $-Mg\\hat z$ applicato nel CM d&agrave; $$\\vec M_O=d\\,\\hat u\\times(-Mg\\hat z)=Mgd\\,(\\hat z\\times\\hat u),\\qquad|\\vec M_O|=Mgd\\sin\\theta,$$ vettore orizzontale, ortogonale all'asse: $\\vec M_O\\cdot\\vec L=0$.<br><b>Modulo fisso, direzione che ruota.</b> Da $d\\vec L/dt=\\vec M_O$ segue $$\\frac{d}{dt}L^2=2\\,\\vec L\\cdot\\vec M_O=0,$$ e anche $\\hat z\\cdot d\\vec L/dt=0$: restano costanti modulo e inclinazione, e la punta di $\\vec L$ percorre un cerchio orizzontale di raggio $L\\sin\\theta$.<br><b>Conto della precessione.</b> In $dt$ la punta avanza di $|d\\vec L|=Mgd\\sin\\theta\\,dt$ lungo quel cerchio, quindi $$d\\phi=\\frac{|d\\vec L|}{L\\sin\\theta}=\\frac{Mgd\\,dt}{I\\omega}\\ \\Longrightarrow\\ \\boxed{\\ \\Omega_p=\\frac{Mgd}{I\\omega}\\ }$$ indipendente da $\\theta$. Coerenza a posteriori: $\\Omega_p\\ll\\omega$ equivale a $\\omega^2\\gg Mgd/I$, cio&egrave; trottola veloce. $\\blacksquare$<br><br><b>Significato fisico.</b> Un momento ortogonale a $\\vec L$ ne ruota la direzione senza cambiarne il modulo, come la forza centripeta fa con $\\vec p$. Di qui la <b>rigidit&agrave; giroscopica</b>: un momento agente per $\\Delta t$ devia l'asse solo di $\\Delta\\phi\\simeq M\\Delta t/(I\\omega)$, tanto meno quanto pi&ugrave; grande &egrave; $L$ &mdash; il giroscopio &laquo;resiste&raquo; (bussole giroscopiche, stabilizzazione di satelliti). La stessa struttura $d\\vec L/dt=\\vec\\mu\\times\\vec B$ con $\\vec\\mu=\\gamma\\vec L$ d&agrave; la <b>precessione di Larmor</b> $\\omega_L=\\gamma B$: lo spin in campo magnetico precede con la medesima matematica, ed &egrave; il cuore della risonanza magnetica."},

{type:6, topic:"Urti tra corpi estesi — centro di percussione",
 q:"Un punto materiale urta un corpo rigido incernierato a un asse fisso. Discuti quali grandezze si conservano e rispetto a quale polo, spiegando perch&eacute; la quantit&agrave; di moto non si conserva, e ricava la posizione del <b>centro di percussione</b>, cio&egrave; il punto d'impatto per cui la cerniera non riceve alcun impulso.",
 prov:"Corpi rigidi — canone universale (da ricontrollare sul Focardi, copia fisica)",
 model:"<b>Impostazione e ipotesi.</b> Corpo rigido di massa $M$, in quiete, ruotabile attorno all'asse fisso per la cerniera $O$; momento d'inerzia $I$ rispetto a quell'asse, CM a distanza $d$ da $O$. Un punto di massa $m$ e velocit&agrave; $v$ lo colpisce a distanza $b$ da $O$, con $\\vec v$ ortogonale alla congiungente e nel piano perpendicolare all'asse che contiene il CM. Ipotesi: urto <b>istantaneo</b> ($\\Delta t\\to0$), asse principale d'inerzia per $O$ (altrimenti la cerniera deve fornire anche coppie).<br><b>Che cosa si conserva.</b> Per $\\Delta t\\to0$ contano solo le forze impulsive (peso e attriti finiti danno $\\vec F\\Delta t\\to0$). L'unica impulsiva esterna &egrave; la reazione $\\vec R$ della cerniera, applicata <b>in $O$</b>: braccio nullo, dunque $\\vec M_O^{\\text{ext}}=0$ e $L_O$ si conserva. Ma $\\vec R$ ha risultante non nulla: la quantit&agrave; di moto <b>non</b> si conserva, e con un polo diverso da $O$ il bilancio dei momenti si sporca.<br><b>Equazione dell'urto.</b> Proiettile conficcato: $$mvb=(I+mb^2)\\,\\Omega\\ \\Longrightarrow\\ \\Omega=\\frac{mvb}{I+mb^2};$$ se rimbalza con $v'$, $mvb=mv'b+I\\Omega$, e nel caso elastico si affianca l'energia.<br><b>Centro di percussione.</b> Siano $J$ l'impulso ricevuto nel punto d'urto e $J_O$ quello della cerniera: il teorema dell'impulso per il CM e il bilancio dei momenti danno $$J+J_O=M\\Omega d,\\qquad Jb=I\\Omega\\ \\Longrightarrow\\ J_O=\\Omega\\Big(Md-\\frac{I}{b}\\Big),$$ che si annulla se e solo se $$\\boxed{\\ b=\\frac{I}{Md}\\ }$$ Con Huygens-Steiner $I=I_{cm}+Md^2$: $b=d+k^2/d>d$ ($k$ raggio giratore rispetto al CM), il centro di percussione sta sempre <b>oltre</b> il CM. Asta omogenea incernierata a un estremo: $I=M\\ell^2/3$, $d=\\ell/2$, $b=\\tfrac23\\ell$. $\\blacksquare$<br><br><b>Significato fisico.</b> $b=I/(Md)$ &egrave; anche la lunghezza ridotta del pendolo composto: centro di percussione e centro di oscillazione coincidono. &Egrave; lo <b>sweet spot</b> della mazza o della racchetta &mdash; colpendo l&agrave; la mano non sente contraccolpo; nell'attrezzo reale &egrave; un compromesso, perch&eacute; contano anche il nodo del primo modo di vibrazione e il coefficiente di restituzione, che il modello rigido ignora. Il metodo &mdash; isolare le impulsive e scegliere il polo che azzera il vincolo &mdash; ritorna nell'approssimazione impulsiva della teoria dell'urto."}

];
